# Generated by Django 5.1.4 on 2025-01-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_learningcenter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='learning_center',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
