# Generated by Django 5.1.4 on 2025-01-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_learning_center_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningCenter',
        ),
    ]
