# Generated by Django 5.1.4 on 2025-01-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_learningcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
